-- tb_map_parity_ram.vhd -- VALUE-PARITY GATE for tm_map_engine_ram.
-- Same map_vectors.txt as tb_map_parity, but the per-map window is generated by
-- tm_rng_gen and then LOADED row-by-row into the engine's internal RAM before
-- the map runs. Checks tm_map_engine_ram == tm_8 run_one_map bit-for-bit.
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use std.textio.all;
library work;
use work.tm_pkg.all;

entity tb_map_parity_ram is
  generic (PATH : string := "ref/map_vectors.txt";
           UNROLL_K : integer := 16; GROUP_UNROLL : integer := 4);
end entity;

architecture sim of tb_map_parity_ram is
  signal clk : std_logic := '0';
  signal rst : std_logic := '1';

  signal gen_start, gen_busy, gen_done : std_logic := '0';
  signal gen_seed : std_logic_vector(15 downto 0);
  signal win_sig  : win_arr_t;

  signal eng_start, eng_busy, eng_done : std_logic := '0';
  signal eng_sin  : state_t;
  signal eng_nib  : std_logic_vector(15 downto 0);
  signal eng_out  : state_t;

  signal wr_en   : std_logic := '0';
  signal wr_row  : std_logic_vector(3 downto 0) := (others => '0');
  signal wr_data : slv1024 := (others => '0');

  function hexdig(c : character) return integer is
  begin
    case c is
      when '0' to '9' => return character'pos(c) - character'pos('0');
      when 'A' to 'F' => return character'pos(c) - character'pos('A') + 10;
      when 'a' to 'f' => return character'pos(c) - character'pos('a') + 10;
      when others     => return 0;
    end case;
  end function;
begin
  clk <= not clk after 5 ns;

  gen : entity work.tm_rng_gen generic map (UNROLL_K=>UNROLL_K)
    port map (clk=>clk, rst=>rst, start=>gen_start, seed_in=>gen_seed,
              busy=>gen_busy, done=>gen_done, win_out=>win_sig);

  eng : entity work.tm_map_engine_ram generic map (GROUP_UNROLL=>GROUP_UNROLL)
    port map (clk=>clk, rst=>rst, start=>eng_start, state_in=>eng_sin,
              nibble=>eng_nib, wr_en=>wr_en, wr_row=>wr_row, wr_data=>wr_data,
              busy=>eng_busy, done=>eng_done, state_out=>eng_out);

  stim : process
    file     fh    : text;
    variable ln    : line;
    variable fst   : file_open_status;
    variable seed16, nib16 : std_logic_vector(15 downto 0);
    variable s256  : string(1 to 256);
    variable sin, sout : state_t;
    variable nvec, nbad : integer := 0;
    variable bad_v : integer := 0;
    variable rowd  : slv1024;
  begin
    wait for 23 ns; rst <= '0';
    wait until rising_edge(clk);

    file_open(fst, fh, PATH, read_mode);
    assert fst = open_ok
      report "cannot open " & PATH & " (build ref/dump_map first)" severity failure;

    while not endfile(fh) loop
      readline(fh, ln); hread(ln, seed16); hread(ln, nib16);
      readline(fh, ln); read(ln, s256);
      for k in 0 to NUM_BYTES-1 loop
        sin(k) := std_logic_vector(to_unsigned(hexdig(s256(2*k+1))*16 + hexdig(s256(2*k+2)), 8));
      end loop;
      readline(fh, ln); read(ln, s256);
      for k in 0 to NUM_BYTES-1 loop
        sout(k) := std_logic_vector(to_unsigned(hexdig(s256(2*k+1))*16 + hexdig(s256(2*k+2)), 8));
      end loop;

      -- regenerate the per-map window
      gen_seed <= seed16;
      gen_start <= '1'; wait until rising_edge(clk) and gen_busy = '1'; gen_start <= '0';
      wait until gen_done = '1'; wait until rising_edge(clk);

      -- LOAD the 16 window rows into the engine RAM
      for r in 0 to 15 loop
        for j in 0 to NUM_BYTES-1 loop
          rowd(8*j+7 downto 8*j) := win_sig(128*r + j);
        end loop;
        wr_data <= rowd; wr_row <= std_logic_vector(to_unsigned(r,4)); wr_en <= '1';
        wait until rising_edge(clk);
      end loop;
      wr_en <= '0';
      wait until rising_edge(clk);

      -- run one map
      eng_sin <= sin; eng_nib <= nib16;
      eng_start <= '1'; wait until rising_edge(clk) and eng_busy = '1'; eng_start <= '0';
      wait until eng_done = '1'; wait until rising_edge(clk);

      bad_v := 0;
      for k in 0 to NUM_BYTES-1 loop
        if eng_out(k) /= sout(k) then bad_v := bad_v + 1; end if;
      end loop;
      if bad_v /= 0 then
        nbad := nbad + 1;
        if nbad <= 4 then
          report "MISMATCH vec=" & integer'image(nvec) & " seed=" & to_hstring(seed16)
               & " bad_bytes=" & integer'image(bad_v) severity warning;
        end if;
      end if;
      nvec := nvec + 1;
    end loop;
    file_close(fh);

    assert nbad = 0
      report "FAIL: " & integer'image(nbad) & "/" & integer'image(nvec) & " mismatched" severity failure;
    report "PASS: tm_map_engine_ram == tm_8 run_one_map for all "
         & integer'image(nvec) & " vectors (RAM window load + read LOCKED)"
      severity note;
    wait;
  end process;
end architecture;
